/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder */

#ifndef _Included_com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder
#define _Included_com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder
 * Method:    startTuner
 * Signature:  (Ljava/nio/ByteBuffer;II)V;
 */
JNIEXPORT void JNICALL Java_com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder_startTuner
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder
 * Method:    decodePDU
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder_decodePDU
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder
 * Method:    decodePDUDirect
 * Signature: (Ljava/nio/ByteBuffer;II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder_decodePDUDirect
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cloudhopper_smpp_transcoder_asynchronous_DefaultAsynchronousDecoder_initialize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
